# -*- coding: utf-8 -*-
"""warehouse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-Dc-ZyI87LjcqAhri_SojQFo2u1wxqX
"""

class Warehouse:
    def __init__(self):
        self.inventory = {}

    def add_goods(self, item, quantity):
        if item in self.inventory:
            self.inventory[item] += quantity
        else:
            self.inventory[item] = quantity

    def remove_goods(self, item, quantity):
        if item in self.inventory and self.inventory[item] >= quantity:
            self.inventory[item] -= quantity
        else:
            print("Not enough stock")

    def inventory_report(self):
        print("Inventory Report")
        for item, qty in self.inventory.items():
            print(item, ":", qty)

    def forecast_demand(self, item):
        if item in self.inventory:
            demand = self.inventory[item] * 2
            print("Forecasted demand for", item, ":", demand)
        else:
            print("Item not found")


w = Warehouse()

while True:
    print("\n1.Add Goods\n2.Remove Goods\n3.Inventory Report\n4.Forecast Demand\n5.Exit")
    choice = int(input("Enter choice: "))

    if choice == 1:
        item = input("Enter item name: ")
        qty = int(input("Enter quantity: "))
        w.add_goods(item, qty)

    elif choice == 2:
        item = input("Enter item name: ")
        qty = int(input("Enter quantity: "))
        w.remove_goods(item, qty)

    elif choice == 3:
        w.inventory_report()

    elif choice == 4:
        item = input("Enter item name: ")
        w.forecast_demand(item)

    elif choice == 5:
        break